[package]
name = "Assignment6Q1"
version = "0.1.0"
authors = ["Mufassar <mufassarbaig@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
